[colors]
background       = '#000000'
black            = '#000000'
blue             = '#7093cb'
cursor           = '#d2b48c'
cyan             = '#6f8e7d'
foreground       = '#d2b48c'
green            = '#90a992'
magenta          = '#d85a47'
red              = '#f16857'
tabs             = '#1a1a1a'
tabs-active      = '#333333'
white            = '#d2b48c'
yellow           = '#da8115'
dim-black        = '#000000'
dim-blue         = '#7093cb'
dim-cyan         = '#6f8e7d'
dim-foreground   = '#d2b48c'
dim-green        = '#90a992'
dim-magenta      = '#d85a47'
dim-red          = '#f16857'
dim-white        = '#d2b48c'
dim-yellow       = '#da8115'
light-black      = '#333333'
light-blue       = '#61c5d8'
light-cyan       = '#6f8e7d'
light-foreground = '#d2b48c'
light-green      = '#90a992'
light-magenta    = '#d85a47'
light-red        = '#f16857'
light-white      = '#ecb490'
light-yellow     = '#da8115'

